project:
  name: "textus-control-center"
  title: "Textus Control Center"
  kind: car
  organization: "org.textus"
  scalaPackage: "org.simplemodeling.textus.controlcenter"
  component:
    name: "textus-control-center"
    className: "TextusControlCenter"
    displayName: "Textus Control Center"
    version: "0.1.0-SNAPSHOT"
    config:
      textus.server.default-port: "18000"

build:
  scalaVersion: "3.3.8"
  dependencies:
    compile:
      - "org.goldenport::goldenport-cncf:0.5.1"
    test:
      - "org.scalatest::scalatest:3.2.19"
      - "org.scalacheck::scalacheck:1.17.1"

publication:
  source_manifest:
    enabled: false

packaging:
  kind: car
  car:
    manifest_metadata:
      boundedContext: "subsystem-operation"
      domain: "system-administration"
    runtime:
      cncf:
        minimum: "0.5.0"
        excluded: []
        tested:
          - "0.5.0"
          - "0.5.1"

warehouse:
  repository_artifacts:
    include:
      - car
    modules:
      - "textus-control-center"
