project:
  namespace: "org.simplemodeling.textus"
  id: "ControlCenter"
  title: "Textus Control Center"
  kind: car
  component:
    displayName: "Textus Control Center"
    version: "0.1.0-SNAPSHOT"
    config:
      textus.server.default-port: "18000"

build:
  scalaVersion: "3.3.8"
  cozyVersion: "0.3.4-SNAPSHOT"
  dependencies:
    compile:
      - "org.goldenport::goldenport-cncf:0.5.2-SNAPSHOT"
    test:
      - "org.scalatest::scalatest:3.2.19"
      - "org.scalacheck::scalacheck:1.17.1"

publication:
  source_manifest:
    enabled: false

packaging:
  kind: car
  car:
    manifest_metadata:
      boundedContext: "subsystem-operation"
      domain: "system-administration"
    runtime:
      cncf:
        minimum: "0.5.2-SNAPSHOT"
        excluded: []
        tested:
          - "0.5.2-SNAPSHOT"

warehouse:
  repository_artifacts:
    include:
      - car
    modules:
      - "textus-control-center"
